---
- hosts: all
  remote_user: root
  tasks:
    - name: test connection
      ping:
      when: ansible_facts['os_family'] == "Centos"
- hosts: windows
  tasks:
    - name: test windows connection
      win_ping:
