---
# tasks file for windows

- hosts: windows
  when: ansible_facts['anisble_os_family'] == 'windows'
  tasks:
    - name: test windows connection
      win_ping:
    - name: write windows file
      win_file:
        path: 'c:\Windows\Temp\ansible-windows.txt'
        state: touch